---
title: "krr"
author: "Group3"
date: "11/17/2021"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage[utf8]{inputenc}
- \usepackage{natbib}
- \bibliographystyle{abbrvnat}
---
\section{Introduction}

\section{Data}
To measure the operational efficiency of six airlines in the United States between 1970-1984 in our sample, we measure the revenue per passenger-mile flown. Earlier research has shown (REF) that key performance indicators total cost of the airline, the fuel price, and the load factor* are important measures to predict operational efficiency. Further, we control for the year of observation, however, we do not use individual dummies for each year, but a continuous variable. This is important as when the model is used to predict a year forward this is not possible with a dummy for the year we are attempting to predict. Finally, a dummy is included for each of the 6 airlines.\\
We use the data from Greene (2003), which has annual observations on 6 airlines on the described variables, 15 observations per airline in total, summary statistics are included in Table XXX. We scale all variables except the airline dummies to create z-scores; $(X – \mu) / \sigma$  where $\mu$ and $\sigma$ are the mean and the standard deviation respectively. This is essential, as our approach is relying on distance between observations, by scaling we ensure equal importance for each variable.

```{r, echo=FALSE}
library(Hmisc)
load('Airline.Rdata')
df <- Airline

Hmisc

```


\section{Method}

\section{Results}
Analysis of the data and models used to predict airlines costs reveals that the airline cost predictions made by our best model are indeed significantly
better than random ($R^2=0.96$).

To arrive at this conclusion, we analyzed different parameters for the different kernels described in the method section as well as compared them to an OLS regression and the package built by \citet{groenemodel}.

For all models, we used the same values for $\lambda$, namely 1, 5, 10, 0.001, 0.01, 0.1, 0.2, 0.5, and 100.

\subsection{KRR with linear kernel}
The analysis of the KRR with linear kernel reveals that the best predictions of the model are provided given higher/lower values for $\lambda$. 

\subsection{Model with RBF kernel}
For the RBF kernel analysis, we defined the $\gamma$ parameters as ... .

The analysis reveals that the best predictions of the model are provided given higher/lower values for $\gamma$ as well as higher/lower values for $\lambda$. 

\section{Discussion}